### ISSUE TITLE
Broken config.toml

### ISSUE THREAD

**Issue by michaelnordmeyer** [Blackstareye/stargazer-layout#21]
While [switching to `config.toml`](https://github.com/Blackstareye/stargazer-layout/commit/79bcbbdc604dccc77ac1c252df4f79c6830000e7#diff-a8920076eb4397a674413ad13dd07ee4e360310f895ea202782659b91483ec1cR30), you introduced a broken setting `hugoVersion`:

```toml
[module]
  [module.hugoVersion]
    extended= true
    hugoVersion=
```

This creates a warning in the deployment pipeline of [themes.gohugo.io](https://github.com/gohugoio/hugoThemesSiteBuilder), where you have [submitted your theme](https://github.com/gohugoio/hugoThemesSiteBuilder/commit/92287b2a01045140bababf5ba0251a305ae7d5c0).

A proper version would look like this:

```toml
[module]
  [module.hugoVersion]
    extended = true
    min = "0.100.0"
```

Set the appropriate minimum version for `min` or remove `hugoVersion=` from your `config.toml`.

Could you please fix this and create a new tag for the released version so that the deployment pipeline can fetch the new version? Thanks.
